New start

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -9,7 +9,7 @@ DEPLOY_BRANCH="gh-pages"
 
 USAGE_MSG="usage: deploy [-h|--help] [-u|--user] [-s|--src SRC_BRANCH] [-d|--deploy DEPLOY_BRANCH] [--verbose] [--no-push]"
 
-while [[ $# > 0 ]]; do
+while [[ $# -gt 0 ]]; do
     key="$1"
 
     case $key in
@@ -49,12 +49,12 @@ echo "Deploying..."
 echo "Source branch: $SRC_BRANCH"
 echo "Deploy branch: $DEPLOY_BRANCH"
 
-read -r -p "Do you want to proceed? [y/N] " response
-if [[ ! $response =~ ^([yY][eE][sS]|[yY])+$ ]]
-then
-    echo "Aborting."
-    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
-fi
+#read -r -p "Do you want to proceed? [y/N] " response
+#if [[ ! $response =~ ^([yY][eE][sS]|[yY])+$ ]]
+#then
+#    echo "Aborting."
+#    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+#fi
 
 # Check if there are any uncommitted changes
 if ! git diff-index --quiet HEAD --; then
